- name: create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/network.html"

- name: copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: copy logo over
  ansible.builtin.copy:
    src: "webpage_logo.png"
    dest: "{{ file_path }}"
    directory_mode: true

- name: display link to inventory report
  ansible.builtin.debug:
    msg: "Please go to http://{{ ansible_host }}/network.html"