- name: create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/windows.html"
    owner: root
    group: root
    mode: '0644'

- name: copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true
    owner: root
    group: root
    mode: '0644'

- name: copy logos over
  ansible.builtin.copy:
    src: "{{ item }}" 
    dest: "{{ file_path }}"
    directory_mode: true
    owner: root
    group: root
    mode: '0644'
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "server.png"

- name: display link to inventory report
  ansible.builtin.debug:
    msg: "Please go to http://{{ ansible_host }}/windows.html"
