- name: Create HTML report
  template:
    src: report.j2
    dest: "{{ file_path }}/windows.html"

- name: Copy CSS over
  copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: Copy logo over
  copy:
    src: "webpage_logo.png"
    dest: "{{ file_path }}"
    directory_mode: true

- name: Display link to Windows report
  debug:
    msg: "Please go to http://{{ansible_host}}/windows.html"